"""
Marketing Automation — Agents Corp
Runs as systemd service. Monitors signups, sends alerts, schedules content.

Scripts:
  signup_monitor  — alerts Telegram on new DeepAPI registrations
  content_scheduler — dev.to poster on schedule
"""
import os, sys, json, time, urllib.request
from datetime import datetime, timezone, timedelta

sys.path.insert(0, '/opt/trading')
sys.path.insert(0, '/opt/trading/agents-corp')
from dotenv import load_dotenv
load_dotenv('/opt/trading/config/.env')
import psycopg2

DB = {
    'host': os.getenv('POSTGRES_HOST'), 'port': int(os.getenv('POSTGRES_PORT', '5432')),
    'user': os.getenv('POSTGRES_USER'), 'password': os.getenv('POSTGRES_PASSWORD'),
    'dbname': os.getenv('POSTGRES_DB'), 'connect_timeout': 5,
}
TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")
DS_KEY = os.getenv("DEEPSEEK_API_KEY", "")

def db(sql, params=None, fetch=False):
    conn = psycopg2.connect(**DB); cur = conn.cursor()
    cur.execute(sql, params)
    r = cur.fetchall() if fetch else None
    conn.commit(); cur.close(); conn.close()
    return r

def tg(text):
    if not TOKEN or not CHAT_ID: return
    payload = json.dumps({'chat_id': CHAT_ID, 'text': text, 'parse_mode': 'HTML'}).encode()
    urllib.request.urlopen(urllib.request.Request(f'https://api.telegram.org/bot{TOKEN}/sendMessage',data=payload,headers={'Content-Type':'application/json'}), timeout=10)

def log(msg): print(f'{datetime.now(timezone.utc).strftime("%H:%M:%S")} | 📣 MKT | {msg}')

# ─── Signup Monitor ────────────────────────────────────────────────

class SignupMonitor:
    def __init__(self):
        self.last_check = datetime.now(timezone.utc)
        self.reported_ids = set()

    def run(self):
        now = datetime.now(timezone.utc)
        rows = db("SELECT id, email, plan, referral_code, created_at FROM api_users WHERE created_at > %s ORDER BY created_at DESC LIMIT 10",
                  (self.last_check,), fetch=True)
        if rows:
            new_users = []
            for r in rows:
                if r[0] not in self.reported_ids:
                    new_users.append(r)
                    self.reported_ids.add(r[0])
            if new_users:
                msg = f'<b>📣 Nuevos registros DeepAPI</b>\n'
                for u in new_users:
                    msg += f'• {u[1][:30]} — <b>{u[2]}</b> plan — ref:{u[3]}\n'
                msg += f'\n<i>Total activos: {len(self.reported_ids)}</i>'
                tg(msg)
                log(f'{len(new_users)} new signups')
        self.last_check = now


# ─── Content Scheduler ─────────────────────────────────────────────

CONTENT_CALENDAR = [
    # (day_of_week, title, format)
    (1, "Cómo usar DeepSeek sin tarjeta de crédito", "tutorial"),
    (3, "De 0 a ChatGPT clone en 50 líneas con DeepAPI", "tutorial"),
    (5, "API de IA para latinos — sin dólares, sin barreras", "article"),
]

class ContentScheduler:
    def run(self):
        now = datetime.now(timezone.utc)
        content = self._get_scheduled_content(now)
        if content:
            self._generate_and_store(content, now)

    def _get_scheduled_content(self, now):
        for day, title, fmt in CONTENT_CALENDAR:
            if now.weekday() == day and now.hour == 10 and now.minute < 5:
                return (title, fmt)
        return None

    def _generate_and_store(self, content, now):
        title, fmt = content
        log(f'Generating: {title}')
        # Store as draft for President review
        draft_path = f'/opt/trading/agents-corp/marketing/drafts/{now.strftime("%Y%m%d")}_{title[:30].replace(" ","_")}.md'
        os.makedirs(os.path.dirname(draft_path), exist_ok=True)

        if DS_KEY:
            prompt = f"Escribe un artículo en español titulado '{title}'. Formato: {fmt}. Incluye ejemplos de código. Termina con CTA para registrarse en DeepAPI. Máximo 800 palabras."
            payload = json.dumps({"model":"deepseek-chat","messages":[{"role":"user","content":prompt}],"max_tokens":1500,"temperature":0.7}).encode()
            req = urllib.request.Request("https://api.deepseek.com/v1/chat/completions",data=payload,headers={"Content-Type":"application/json","Authorization":f"Bearer {DS_KEY}"})
            try:
                resp = urllib.request.urlopen(req, timeout=60)
                result = json.loads(resp.read())["choices"][0]["message"]["content"]
                with open(draft_path, 'w') as f: f.write(f"# {title}\n\n{result}\n\n---\n*Generated by DeepAPI Content Scheduler*")
                log(f'Draft saved: {draft_path}')
                tg(f'📝 <b>Contenido generado</b>\n{title}\nRevisar: <code>{draft_path}</code>')
            except Exception as e:
                log(f'LLM error: {e}')


# ─── Main Loop ────────────────────────────────────────────────────

def main():
    log('Marketing automation online')
    signup_monitor = SignupMonitor()
    content_scheduler = ContentScheduler()
    while True:
        try:
            signup_monitor.run()
            content_scheduler.run()
            time.sleep(300)  # every 5 min
        except KeyboardInterrupt: break
        except Exception as e: log(f'Error: {e}'); time.sleep(60)

if __name__ == '__main__':
    main()
